#!/bin/sh
# Xcode Cloud: runs after clone, before dependency resolution and the build.
#
# The .xcodeproj is git-ignored (generated by XcodeGen from project.yml), so
# CI must generate it before Xcode Cloud can build anything. We also stamp
# Xcode Cloud's build number into the project so every TestFlight upload has
# a unique CFBundleVersion without hand-bumping CURRENT_PROJECT_VERSION.
set -e

cd "$CI_PRIMARY_REPOSITORY_PATH"

brew install xcodegen

# Stamp the CI build number (local builds keep the number in project.yml).
if [ -n "$CI_BUILD_NUMBER" ]; then
  sed -i '' "s/^\( *CURRENT_PROJECT_VERSION:\).*/\1 \"$CI_BUILD_NUMBER\"/" project.yml
fi

xcodegen generate

# Xcode Cloud disables automatic SPM resolution and requires a committed
# Package.resolved — but the generated project's copy is git-ignored with the
# rest of the .xcodeproj. The canonical pin lives at the repo root (refresh it
# with `make lock` after changing dependencies); copy it into place.
mkdir -p SalahBuddy.xcodeproj/project.xcworkspace/xcshareddata/swiftpm
cp Package.resolved SalahBuddy.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved

# Self-heal: if project.yml added/changed dependencies since the committed
# pin, resolve them here instead of failing with "a resolved file is
# required". The ios.yml GitHub workflow persists the refreshed pin back to
# the repo, so this drift lasts one build at most.
xcodebuild -resolvePackageDependencies -project SalahBuddy.xcodeproj -scheme SalahBuddy
