#!/bin/sh
# Xcode Cloud: runs after clone, before dependency resolution and the build.
#
# The .xcodeproj is git-ignored (generated by XcodeGen from project.yml), so
# CI must generate it before Xcode Cloud can build anything. We also stamp
# Xcode Cloud's build number into the project so every TestFlight upload has
# a unique CFBundleVersion without hand-bumping CURRENT_PROJECT_VERSION.
set -e

cd "$CI_PRIMARY_REPOSITORY_PATH"

brew install xcodegen

# Stamp the CI build number (local builds keep the number in project.yml).
if [ -n "$CI_BUILD_NUMBER" ]; then
  sed -i '' "s/^\( *CURRENT_PROJECT_VERSION:\).*/\1 \"$CI_BUILD_NUMBER\"/" project.yml
fi

xcodegen generate
